name: appmanager

services:

  proxy:
    build:
      context: ..
      dockerfile: Dockerfile-proxy
    ports:
      - "20080:80"
      - "443:443"
    # run ./scripts/setup to generate this file
    # see: ./scripts/setup:generate_web_proxy_config
    env_file: ../tmp/web-proxy-configs/web-proxy.env
    restart: always

  service:
    image: terra-app-manager
    depends_on:
      - database
    environment:
      - DATABASE_HOSTNAME=database
    ports:
      - "8080:8080"

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=dbuser    # default: postgres
#      - POSTGRES_DB=appmanager_db
    ports:
      - "5432:5432"
    volumes:
      - ../build/tmp/postgres-data:/var/lib/postgresql/data
      - ./init-db/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
