#!/usr/bin/env bash
# this shell script is responsible for:
# - making sure your environment is setup, and
# - setting up a database environment locally for you to use
set -e #-x

usage() {
  cat <<-'EOF'
usage: $0 [-c|--clean-db] [-h|--help]

[-c|--clean-db]       clean the database
[-h|--help]           print this help text
EOF
}

# script variables and defaults
source $(dirname $0)/init.sh

# the list of tools required to be installed to interact with this repo
# this is meant to verify what is also in the ./README.md#environment-setup section
TOOLS=(java docker)
clean_db_opt=""


# process command-line options (if any)
die() { log_error "$*" >&2; echo ""; usage; exit 2; }  # complain to STDERR and exit with error
needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }

while getopts ch-: OPT; do  # allow -h and -- "with arg"
  # support long options: https://stackoverflow.com/a/28466267/519360
  if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
    OPT="${OPTARG%%=*}"       # extract long option name
    OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
    OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
  fi
  case "$OPT" in
    c | clean-db )       clean_db_opt="--clean-db" ;;
    h | help )           usage; exit 0 ;;
    \? )                 usage; exit 2 ;;  # bad short option (error reported via getopts)
    * )                  die "Illegal option --$OPT" ;;            # bad long option
  esac
done
shift $((OPTIND-1)) # remove parsed options and args from $@ list


# process positional arguments (if any)

MSG_PREFIX="[$(basename $SCRIPTS_DIR)/$(basename $0)]"
log() {
  log_info "$MSG_PREFIX ${@}"
}

generate_web_proxy_config() {
  local _cluster=terra-dev
  local _outdir=${TMP_DIR}/web-proxy-configs
  mkdir -p ${_outdir}

  echo "Configuring access to ${_cluster}..."
  echo "(Note: non-split-tunnel VPN is required when working remotely)"
  gcloud container clusters get-credentials --zone us-central1-a --project broad-dsde-dev ${_cluster}

  kubectl -n terra-dev get configmap appmanager-oauth2-configmap -o 'go-template={{index .data "oauth2.conf"}}' > ${_outdir}/oauth2.conf
  ## Local dev uses a macOS-specific docker replacement hostname for locahost, so replace all instances in the proxy config.
  kubectl -n terra-dev get configmap appmanager-site-configmap -o 'go-template={{index .data "site.conf"}}' | sed 's/localhost/host\.docker\.internal/g' > ${_outdir}/site.conf
  #
  ## local.dsde-dev.broadinstitute.org cert
  kubectl -n local-dev get secrets local-dev-cert -o 'go-template={{ index .data "tls.crt" | base64decode }}' > ${_outdir}/server.crt
  kubectl -n local-dev get secrets local-dev-cert -o 'go-template={{ index .data "tls.key" | base64decode }}' > ${_outdir}/server.key
  #
  ## Get proxy env vars
  {
    echo B2C_APPLICATION_ID=$(kubectl -n terra-dev get secret appmanager-proxy-b2c-secrets-eso -o 'go-template={{ index .data "application-id" }}' | base64 --decode)
  } > ${_outdir}/web-proxy.env
}

log "verifying required tools are installed"
check_required_tools "${TOOLS[@]}" || exit 1;
log ""

log "generating web-proxy information"
generate_web_proxy_config
log ""


log "setting up service database"
$(dirname $0)/run-db ${clean_db_opt} start
log "... database setup COMPLETE"
